language: node_js
node_js:
- "7"

before_script:
- npm install

script:
- echo "Hello!!"

deploy:
  provider: npm
  email: k.wongsin@togetherteam.co.th
  api_key: a570df7b-42c2-44c4-b655-12089ce20851
  on:
    tags: true
  skip_cleanup: true
